package com.easybilling.engine;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Result of executing rule actions.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class RuleActionResult {
    
    /**
     * Whether all actions executed successfully.
     */
    @Builder.Default
    private boolean success = true;
    
    /**
     * Results from individual actions.
     */
    @Builder.Default
    private Map<String, Object> results = new HashMap<>();
    
    /**
     * Messages generated by actions.
     */
    @Builder.Default
    private List<String> messages = new ArrayList<>();
    
    /**
     * Errors that occurred during action execution.
     */
    @Builder.Default
    private List<String> errors = new ArrayList<>();
    
    /**
     * Add a result from an action.
     */
    public void addResult(String key, Object value) {
        results.put(key, value);
    }
    
    /**
     * Add a message.
     */
    public void addMessage(String message) {
        messages.add(message);
    }
    
    /**
     * Add an error.
     */
    public void addError(String error) {
        errors.add(error);
        success = false;
    }
}
